[project]
name = "fastapi-mongodb-restapi"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.115.4",
    "pymongo>=4.10.1",
    "uvicorn>=0.32.0",
]
